import { useNavigate } from "react-router-dom";
import PublicNav from "../../components/PublicNav";
import PublicFooter from "../../components/PublicFooter";
import "../public/public-pages.css";

const TOOLS = [
  { icon: "🎯", title: "Marketing Strategy Generator", desc: "Build a complete go-to-market strategy tailored to your product and audience." },
  { icon: "📅", title: "Content Calendar", desc: "Plan weeks of content at once with AI-suggested topics and publishing schedules." },
  { icon: "📱", title: "Social Media Generator", desc: "Create platform-optimised posts for Facebook, Instagram, LinkedIn, X, and TikTok." },
  { icon: "✍️", title: "Blog Generator", desc: "Draft long-form articles, listicles, and thought leadership content in minutes." },
  { icon: "🔍", title: "SEO Keyword Planner", desc: "Discover high-value keywords and build a content strategy around search intent." },
  { icon: "📧", title: "Email Campaign Generator", desc: "Write full email sequences — welcome, nurture, promo — that convert." },
  { icon: "📣", title: "Advertising Copy Generator", desc: "Create compelling ad copy for Google, Meta, and LinkedIn campaigns." },
  { icon: "📊", title: "Marketing Analytics", desc: "Track your marketing performance and get AI-powered optimization recommendations." },
];

const PLATFORMS = ["Facebook", "Instagram", "LinkedIn", "X (Twitter)", "TikTok"];

export default function MarketingStudio() {
  const navigate = useNavigate();

  return (
    <div className="pub-page">
      <PublicNav />

      <section className="pub-hero">
        <p className="pub-hero-label">✦ PLATFORM — MARKETING STUDIO</p>
        <h1>Create. Publish. Grow.<br />With AI-Powered Marketing</h1>
        <p>
          The Marketing Studio gives you a complete content and marketing engine —
          from strategy to social posts to email campaigns — all generated by AI.
        </p>
        <div className="pub-hero-actions">
          <button className="btn-white" onClick={() => navigate("/dashboard")}>
            Launch Marketing Studio →
          </button>
          <button className="btn-outline-white" onClick={() => navigate("/signup")}>
            Sign Up Free
          </button>
        </div>
      </section>

      <div className="pub-stats-strip">
        {[
          { value: "7+", label: "Marketing Tools" },
          { value: "5", label: "Social Platforms" },
          { value: "10x", label: "Faster Content Creation" },
          { value: "Free", label: "To Start" },
        ].map((s) => (
          <div className="pub-stat" key={s.label}>
            <strong>{s.value}</strong>
            <span>{s.label}</span>
          </div>
        ))}
      </div>

      <section className="pub-section bg-white">
        <p className="pub-section-label">✦ TOOLS INCLUDED</p>
        <h2>Your Complete Marketing Engine</h2>
        <p className="pub-section-sub">
          Stop spending hours on content. Let Voxora's Marketing Studio generate
          your entire marketing strategy and content calendar in one session.
        </p>
        <div className="pub-grid">
          {TOOLS.map((t) => (
            <div className="pub-card" key={t.title}>
              <div className="pub-card-icon">{t.icon}</div>
              <h3>{t.title}</h3>
              <p>{t.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="pub-section bg-gray">
        <p className="pub-section-label">✦ SOCIAL MEDIA</p>
        <h2>One Tool. Every Platform.</h2>
        <p className="pub-section-sub">Generate optimised content for every social channel without switching tools.</p>
        <div style={{ display: "flex", gap: 12, justifyContent: "center", flexWrap: "wrap" }}>
          {PLATFORMS.map((p) => (
            <div key={p} style={{ background: "#fff", border: "1px solid #e5e7eb", borderRadius: 14, padding: "16px 24px", fontWeight: 700, color: "#0f172a", fontSize: 15, boxShadow: "0 2px 8px rgba(0,0,0,0.04)" }}>
              {p}
            </div>
          ))}
        </div>
      </section>

      <section className="pub-cta">
        <h2>Ready to Scale Your Marketing?</h2>
        <p>Create a full month of content in a single afternoon with the Marketing Studio.</p>
        <div className="pub-cta-actions">
          <button className="btn-white" onClick={() => navigate("/dashboard")}>Open Marketing Studio →</button>
          <button className="btn-outline-white" onClick={() => navigate("/solutions/creators")}>For Creators</button>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}
