// ── V6.1 Investor & Pitch Studio — Executive Summary Generator ───────────────
import { useState } from "react";
import { useProjects }  from "../../context/ProjectContext";
import { useActivity }  from "../../context/ActivityContext";
import { useToast }     from "../../context/ToastContext";
import { useAI }        from "../../hooks/useAI";
import { useAIContext } from "../../context/AIContext";
import DemoBanner       from "../../components/DemoBanner";
import { escapeHtml }   from "../../services/storage/SafeStorage";
import "./Workspace.css";
import "./InvestorStudio.css";

interface Props { setWorkspace: (w: string) => void }

function downloadFile(filename: string, content: string, mimeType: string) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([content], { type: mimeType }));
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

export default function ExecSummaryGen({ setWorkspace }: Props) {
  const { saveProject }  = useProjects();
  const { addActivity }  = useActivity();
  const { showToast }    = useToast();
  const { isDemoMode }   = useAIContext();
  const { generate, isLoading } = useAI("executiveSummary");

  const [companyName,    setCompanyName]    = useState("");
  const [problem,        setProblem]        = useState("");
  const [solution,       setSolution]       = useState("");
  const [market,         setMarket]         = useState("");
  const [businessModel,  setBusinessModel]  = useState("");
  const [traction,       setTraction]       = useState("");
  const [team,           setTeam]           = useState("");
  const [fundingAsk,     setFundingAsk]     = useState("");
  const [summary,        setSummary]        = useState("");

  const generate_ = async () => {
    if (!companyName.trim() || !problem.trim() || !solution.trim()) return;

    const prompt = `You are an expert at writing one-page investor executive summaries.

Write a professional, compelling one-page executive summary for this startup:

Company: ${companyName}
Problem: ${problem}
Solution: ${solution}
Market Opportunity: ${market}
Business Model: ${businessModel}
Traction / Milestones: ${traction}
Team: ${team}
Funding Ask: ${fundingAsk}

Format the executive summary with these clearly labeled sections:
1. Company Overview
2. The Problem
3. Our Solution
4. Market Opportunity
5. Business Model
6. Traction & Milestones
7. The Team
8. Funding Ask & Use of Funds

Keep it concise (one page), investor-focused, and compelling. Use bullet points within sections. 
End with a strong closing statement about why now is the right time and why this team will win.`;

    const result = await generate(prompt);
    if (!result) return;
    setSummary(result);
    addActivity({
      type: "exec_summary_generated",
      title: "Executive Summary Generated",
      description: `One-page executive summary generated for "${companyName}".`,
      category: "Investor", icon: "📄",
    });
    showToast("📄 Executive summary generated!");
  };

  const save = () => {
    if (!summary) return;
    saveProject({
      id: Date.now().toString(),
      title: `Executive Summary — ${companyName}`,
      category: "Executive Summary",
      createdAt: new Date().toISOString(),
      notes: summary,
    });
    addActivity({
      type: "exec_summary_saved",
      title: "Executive Summary Saved",
      description: `Executive summary for "${companyName}" saved.`,
      category: "Investor", icon: "📄",
    });
    showToast("💾 Executive summary saved!");
  };

  const exportMarkdown = () => {
    const md = `# ${companyName} — Executive Summary\n\n${summary}`;
    downloadFile(`${companyName.replace(/\s+/g, "-")}-executive-summary.md`, md, "text/markdown");
    showToast("📄 Markdown exported!");
  };

  const exportJSON = () => {
    const data = { companyName, problem, solution, market, businessModel, traction, team, fundingAsk, summary, generatedAt: new Date().toISOString() };
    downloadFile(`${companyName.replace(/\s+/g, "-")}-executive-summary.json`, JSON.stringify(data, null, 2), "application/json");
    showToast("📦 JSON exported!");
  };

  const exportPDF = () => {
    const safeCompanyName = escapeHtml(companyName);
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${safeCompanyName} — Executive Summary</title>
<style>
  body { font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; padding: 60px; max-width: 800px; margin: auto; color: #111; font-size: 15px; line-height: 1.7; }
  h1 { font-size: 28px; color: #6C63FF; border-bottom: 3px solid #6C63FF; padding-bottom: 12px; }
  h2 { font-size: 18px; color: #1e3a8a; margin: 24px 0 8px; }
  p, li { color: #374151; }
  footer { margin-top: 40px; font-size: 12px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 12px; }
</style></head><body>
<h1>${safeCompanyName} — Executive Summary</h1>
<div style="white-space: pre-wrap">${escapeHtml(summary)}</div>
<footer>Generated by Voxora Investor Studio · ${new Date().toLocaleDateString()}</footer>
</body></html>`;
    const win = window.open("", "_blank");
    if (win) { win.document.write(html); win.document.close(); setTimeout(() => win.print(), 500); }
    showToast("🖨️ PDF print dialog opened!");
  };

  return (
    <div className="workspace-container" style={{ maxWidth: 760 }}>
      <button className="back-btn" onClick={() => setWorkspace("investorStudio")}>← Investor Studio</button>
      <div style={{ fontSize: 36, marginBottom: 8 }}>📄</div>
      <h1>Executive Summary Generator</h1>
      <p className="workspace-subtitle">One-page investor summary — AI-generated from your business plan details.</p>

      {isDemoMode && <DemoBanner onConfigure={() => setWorkspace("aiSettings")} />}

      <div className="workspace-form">
        <input
          className="workspace-input"
          placeholder="Company name *"
          value={companyName}
          onChange={e => setCompanyName(e.target.value)}
        />
        <textarea
          className="workspace-textarea"
          placeholder="The problem you solve *"
          value={problem}
          onChange={e => setProblem(e.target.value)}
          rows={3}
        />
        <textarea
          className="workspace-textarea"
          placeholder="Your solution *"
          value={solution}
          onChange={e => setSolution(e.target.value)}
          rows={3}
        />
        <textarea
          className="workspace-textarea"
          placeholder="Market opportunity (TAM, SAM, SOM)"
          value={market}
          onChange={e => setMarket(e.target.value)}
          rows={2}
        />
        <textarea
          className="workspace-textarea"
          placeholder="Business model (how you make money)"
          value={businessModel}
          onChange={e => setBusinessModel(e.target.value)}
          rows={2}
        />
        <textarea
          className="workspace-textarea"
          placeholder="Traction & milestones (revenue, users, partnerships, etc.)"
          value={traction}
          onChange={e => setTraction(e.target.value)}
          rows={2}
        />
        <textarea
          className="workspace-textarea"
          placeholder="Team (founders and key hires)"
          value={team}
          onChange={e => setTeam(e.target.value)}
          rows={2}
        />
        <input
          className="workspace-input"
          placeholder="Funding ask (e.g. $2M Seed at $10M pre-money valuation)"
          value={fundingAsk}
          onChange={e => setFundingAsk(e.target.value)}
        />
        <button
          className="workspace-btn"
          onClick={generate_}
          disabled={!companyName.trim() || !problem.trim() || !solution.trim() || isLoading}
        >
          {isLoading ? "⏳ Generating…" : "📄 Generate Executive Summary"}
        </button>
      </div>

      {summary && (
        <div className="workspace-results">
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
            <h3 style={{ margin: 0 }}>📄 Executive Summary</h3>
            <div style={{ display: "flex", gap: 8 }}>
              <button className="is-export-btn" onClick={exportMarkdown}>📄 MD</button>
              <button className="is-export-btn" onClick={exportJSON}>📦 JSON</button>
              <button className="is-export-btn" onClick={exportPDF}>🖨️ PDF</button>
            </div>
          </div>
          <textarea
            className="workspace-textarea"
            value={summary}
            onChange={e => setSummary(e.target.value)}
            rows={24}
            style={{ fontSize: 14, lineHeight: 1.7 }}
          />
          <button className="workspace-btn workspace-save-btn" onClick={save}>
            💾 Save Executive Summary
          </button>
        </div>
      )}

      {!summary && !isLoading && (
        <div className="workspace-empty">
          <div className="workspace-empty-icon">📄</div>
          <p>Fill in your business details above to generate a one-page investor executive summary.</p>
        </div>
      )}
    </div>
  );
}
